"""Re-export stub — single canonical source is packages/delivery-workflow/lib/contract.py."""
from lib.contract import *  # noqa: F401,F403

# Explicit __all__ to help static analyzers
from lib.contract import (
    CC_VERSION,
    HEADER_FIELDS,
    STATUS_VALUES,
    REQUIRED_SECTIONS,
    FINDINGS_SECTION_ALIASES,
    OPEN_QUESTIONS_SECTION_ALIASES,
    TRACE_OWNED_METRICS,
    AGENT_REPORTED_METRICS,
    R_RULES,
    ARTIFACT_PATH_TEMPLATE,
    NEXT_CONSUMER_USER_SENTINEL,
    HEADER_REQUIRED_FIELDS,
    NO_PROSE_PARSING_RULE,
)

__all__ = [
    "CC_VERSION",
    "HEADER_FIELDS",
    "STATUS_VALUES",
    "REQUIRED_SECTIONS",
    "FINDINGS_SECTION_ALIASES",
    "OPEN_QUESTIONS_SECTION_ALIASES",
    "TRACE_OWNED_METRICS",
    "AGENT_REPORTED_METRICS",
    "R_RULES",
    "ARTIFACT_PATH_TEMPLATE",
    "NEXT_CONSUMER_USER_SENTINEL",
    "HEADER_REQUIRED_FIELDS",
    "NO_PROSE_PARSING_RULE",
]
